# Generated by Django 4.2.26 on 2025-11-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('zerodha_user_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('zerodha_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('zerodha_api_secret', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': True,
            },
        ),
    ]
