# Generated by Django 4.2.26 on 2025-11-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Users',
        ),
        migrations.AlterModelTable(
            name='users',
            table='tfw_users',
        ),
    ]
