# Generated by Django 4.2.26 on 2025-11-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EOD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('datetime', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('oi', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tfw_eod',
                'managed': True,
                'indexes': [models.Index(fields=['symbol', 'datetime'], name='tfw_eod_symbol_4629f5_idx')],
            },
        ),
    ]
