# Generated by Django 4.2.26 on 2025-11-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eod',
            constraint=models.UniqueConstraint(fields=('symbol', 'datetime'), name='unique_symbol_datetime'),
        ),
    ]
