# Generated by Django 4.2.26 on 2025-11-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_eod_unique_symbol_datetime'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eod',
            name='unique_symbol_datetime',
        ),
        migrations.AddConstraint(
            model_name='eod',
            constraint=models.UniqueConstraint(fields=('symbol', 'datetime'), name='unique_symbol_datetime_v2'),
        ),
    ]
