# Generated by Django 4.2.26 on 2025-11-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_eod_unique_symbol_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eod',
            name='tfw_eod_symbol_4629f5_idx',
        ),
    ]
