# Generated by Django 5.2.8 on 2025-12-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_eod_tfw_eod_symbol_4629f5_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='IData15m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tfw_idata_15m',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('symbol', 'datetime'), name='unique_symbol_datetime_15m')],
            },
        ),
        migrations.CreateModel(
            name='IData75m',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tfw_idata_75m',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('symbol', 'datetime'), name='unique_symbol_datetime_75m')],
            },
        ),
    ]
