# Generated by Django 5.2.8 on 2025-12-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_eod_id_alter_idata75m_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
