# Generated by Django 5.2.8 on 2025-12-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_eod_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('instrument_token', models.BigIntegerField(primary_key=True, serialize=False)),
                ('exchange_token', models.BigIntegerField()),
                ('tradingsymbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('last_price', models.FloatField()),
                ('expiry', models.DateField(blank=True, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('tick_size', models.FloatField()),
                ('lot_size', models.IntegerField()),
                ('instrument_type', models.CharField(max_length=10)),
                ('segment', models.CharField(max_length=20)),
                ('exchange', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tfw_instruments',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('tradingsymbol', 'exchange'), name='unique_tradingsymbol_exchange')],
            },
        ),
    ]
